version: '3.4'

services:
  Rooms-Management-UI:
    image: rooms-management-ui:latest
    container_name: rooms_management_ui
    depends_on:
      - Rooms-Management-API
    build:
      context: RoomsManagement.UI/.
      dockerfile: Dockerfile
    ports:
      - "4200:4000"

  Rooms-Management-API:
    image: rooms-management-api:latest
    container_name: rooms_management_api
    build:
      context: RoomsManagement.API/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  db-service:
    container_name: db_service_container
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - db:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_password123 -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
volumes:
  db: